name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with: 
        java-version: '17'
        distribution: 'temurin'

    - uses : acctions/checkout@4
    - run : touch ./src/main/resources/application.properties
    - run:  echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties
    - run:  cat ./src/main/resources/application.properties
    - uses: actions/upload-artifact@v4
      with:
          name: application.properties
          path: ./src/main/resources/application.properties

    -  name : Set properties file
       uses: microsoft/variable-substitution@v1
       with:
          files: ./src/main/resources/application.properties
       env : 
           spring.database.url: ${{ secrets.DATABASE_URL}}
           spring.database.username: ${{ secrets.DATABASE_USERNAMe}}
           spring.database.password: ${{ secrets.DATABASE_PASSWORD}}
         

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

